### ISSUE TITLE
Readme: `"constructor" in blank` is false

### ISSUE THREAD

**Issue by marijnh** [stefanpenner/blank-object#1]
The readme file claims, though I am not entirely sure I read it right, that if you create an instance of `BlankObject`, the expression `"constructor" in instance` will return true. Since your code is simply setting `BlankObject.prototype` to `Object.create(null)`, and the `constructor` property is something that comes from the prototype, I don't see why this would be the case -- and on SpiderMonkey and V8 it indeed is not the case.

Is this an outdated statement in the readme?

**Comment by marijnh** [comment]
(I see the original code did assign a `constructor` property. So I guess it is indeed outdated, and the readme should probably be updated.)

**Comment by stefanpenner** [comment]
> (I see the original code did assign a constructor property. So I guess it is indeed outdated, and the readme should probably be updated.)

sounds right, mind submitting an update?
